version: "3.7"

services:
  mysql:
    image: mysql
    container_name: mysql_on_docker
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"  