CREATE DATABASE sql_course;
USE sql_course;
CREATE TABLE teacher(id INT AUTO_INCREMENT PRIMARY KEY, surname VARCHAR(255) NOT NULL);
CREATE TABLE lesson(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR (255) NOT NULL, teacher_id INT NOT NULL, FOREIGN KEY (teacher_id) references teacher(id));
INSERT into teacher (surname) value ("Ivanov");
INSERT into teacher (surname) value ("Petrov");
INSERT into teacher (surname) value ("Sidorov");
INSERT into teacher (surname) value ("Petrov");
INSERT into teacher (surname) value ("Chizhkin");
INSERT into teacher (surname) value ("Petrov");
INSERT into teacher (surname) value ("Abdulkanzadoyev");
SELECT * FROM teacher;
SELECT id FROM teacher;
SELECT surname FROM teacher;
SELECT id, surname, surname FROM teacher;
SELECT DISTINCT surname FROM teacher;
SELECT * FROM teacher WHERE id=3;
SELECT * FROM teacher WHERE id>3;
SELECT * FROM teacher WHERE surname="Petrov";
SELECT * FROM teacher WHERE surname="petrov";
SELECT * FROM teacher WHERE surname="petrov" LIMIT 2;
SELECT * FROM teacher LIMIT 2;
SELECT id AS "identifier", surname AS 'familia' FROM teacher; 
SELECT * FROM teacher ORDER BY surname;
SELECT * FROM teacher ORDER BY id DESC;
ALTER TABLE teacher ADD age INT;
SELECT * FROM teacher;
UPDATE teacher SET age=20 WHERE id=1;
UPDATE teacher SET age=30 WHERE id=2;
UPDATE teacher SET age=40 WHERE id=3;
UPDATE teacher SET age=50 WHERE id>3;
SELECT * FROM teacher;
UPDATE teacher SET age=20 WHERE id=1;
UPDATE teacher SET age=25 WHERE id=2;
UPDATE teacher SET age=30 WHERE id=3;
UPDATE teacher SET age=35 WHERE id=4;
UPDATE teacher SET age=40 WHERE id=5;
UPDATE teacher SET age=45 WHERE id=6;
UPDATE teacher SET age=50 WHERE id>7;
SELECT * FROM teacher;
SELECT * FROM teacher WHERE surname LIKE "%rov";
SELECT * FROM teacher WHERE surname LIKE "Pe%";
SELECT * FROM teacher WHERE surname LIKE "%an%";
SELECT * FROM teacher WHERE surname LIKE "P%ov";
SELECT * FROM teacher WHERE id > 2 AND age < 45;
USE sql_course;
SELECT * FROM teacher WHERE id > 2 AND age < 45;
SELECT * FROM teacher WHERE id > 2 OR age < 45;



