version: "3.7"

services:
  mysql:
    image: mysql
    command: --lower_case_table_names=1
    container_name: mysql_docker
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"  
  # api:
  #   image: api
  #   build: ../api
  #   ports:
  #     - "4000:4000"